ef_connect:
    path:  /efconnect/{instance}/{homeFolder}
    defaults: { _controller: FMElfinderBundle:ElFinder:load, instance: default, homeFolder: '' }
elfinder:
    path: /elfinder/{instance}/{homeFolder}
    defaults: { _controller: FMElfinderBundle:ElFinder:show, instance: default, homeFolder: '' }
